### ISSUE TITLE
"GdbLocal my_debug_app" return E119:gdb#Spawn too few argument

### ISSUE THREAD

**Issue by jkunlin** [huawenyu/neogdb.vim#1]

**Comment by huawenyu** [comment]
Mostly I'm working under GdbRemote mode, which bind to <F2>.
The following suppose our local execute file is t1 come from:
1. build a debug version `t1`
    `gcc -g -O0 -o t1 t1.c`
2. vim command:
    `:GdbLocal confloc#me t1 ""`

Have fun :)

**Comment by jkunlin** [comment]
Thanks very much, it works now!
But there are several problems:
1. There are too many windows opened, including one useless terminal at top-left.
2. Set breakpoints  using terminal commands doesn't show in source codes correctly.
3. Is there any convenient way to exit the debug session, including clear the sign column?

**Comment by jkunlin** [comment]
In the gdb terminal buffer, the last command is always "parser_bt ". Therefore I can't use <enter> to repeat last command. Could it be fixed?

I like this plugin very much, it works quite fluent than ConqueGDB.

**Comment by huawenyu** [comment]
> 1. There are too many windows opened, including one useless terminal at top-left.

Now I close one window and one tab when GdbLocal

> 2. Set breakpoints using terminal commands doesn't show in source codes correctly.

If set breakpoint to all function of a file.c:

    <gdb> rbreak file.c:.

So it's not easy for us to hold the all breakpoint under such case.
Even more if user set a breakpoint with complicated condition, how for us record the breakpoint detail into local file '.gdb.breaks' for restart breakpoint restore?
So far here only support easy breakpoint type from <F9>: function or linenumber.

> 3.  Is there any convenient way to exit the debug session, including clear the sign column?

What I do just exit the neovim, restart neovim if want to debug again.
It easy for us to do keymap like: nnoremap <C-q> :<c-u>qa!<cr>

> 4. always "parser_bt "

Have remove this command.

**Comment by jkunlin** [comment]
Thank you for the swift reply!
But at the beginning, there are some errors:
Error detected while processing function gdb#Spawn:                                                                                            
line  100:                                                                                                                                     
E716: Key not present in Dictionary: gdbserver                                                                                                 
E15: Invalid expression: g:state_ctx.window['gdbserver']                                                                                       
line  101:                                                                                                                                     
E716: Key not present in Dictionary: job                                                                                                       
E15: Invalid expression: g:state_ctx.window['job']                                                                                             
line  103:                                                                                                                                     
E121: Undefined variable: win_gdbserver                                                                                                        
E15: Invalid expression: win_gdbserver                                                                                                         
line  104:                                                                                                                                     
E121: Undefined variable: win_job                                                                                                              
E15: Invalid expression: win_job                                                                                                               
line  106:                                                                                                                                     
E121: Undefined variable: win_gdbserver                                                                                                        
E15: Invalid expression: win_gdbserver._client_id                                                                                              
line  107:                                                                                                                                     
E121: Undefined variable: win_job

BTW, Is there any way to configure the windows by users?

**Comment by huawenyu** [comment]
1. Use `<F2>` to toggle the remote or local mode.

If the program is t1, the command of local should be:  `GdbLocal confloc#me t1`
I have test local and it works ok.

```vim
function! GdbLocalRemoteStr()
    if s:gdb_local_remote
        let s:gdb_local_remote = 0
        return 'GdbRemote confos#me sysinit/init 10.1.1.125:444'
    else
        let s:gdb_local_remote = 1
        return 'GdbLocal confloc#me t1'
    endif
endfunction
```
nnoremap `<F2>`: <c-u><C-\>e GdbLocalRemoteStr()<cr>
cnoremap `<F2>`: <c-u><C-\>e GdbLocalRemoteStr()<cr>


2. Is there any way to configure the windows by users?

```vim
function! confloc#me() abort
    " user special config
    let this = {
        \ "Scheme" : 'gdb#SchemeCreate',
        \ "autorun" : 1,
        \ "reconnect" : 0,
        \ "conf_gdb_cmd" : ['gdb -q -f', 'a.out'],
        \ "conf_server_cmd" : ["$SHELL",],
        \ "conf_server_addr" : ["",],
        \ "window" : [
        \   {   "name":   "gdbserver",
        \       "status":  0,             |" here diable the gdbserver in local mode
```

But not suggest to disable the window, for local mode, there only have one more window for gdb command.

**Comment by jkunlin** [comment]
It works but still with the same error messages.

As for the configuration, I mean if I can arrange the windows position, such as put the source code at top, the gdb command window below, and close the other two windows (location and bt windows).

Thanks for the patience.

**Comment by huawenyu** [comment]
1. It works but still with the same error messages.

No error message now. :laughing: 

2. config the windows position:

```diff
@@ -13,9 +13,10 @@ function! confloc#me() abort
         \ "Scheme" : 'gdb#SchemeCreate',
         \ "autorun" : 1,
         \ "reconnect" : 0,
+        \ "showbreakpoint" : 0,
+        \ "showbacktrace" : 0,
+        \ "conf_gdb_layout" : ["sp"],
```

**Comment by jkunlin** [comment]
It is cool!
