### ISSUE TITLE
layout

### ISSUE THREAD

**Issue by ErikLambrechts** [huawenyu/neogdb.vim#10]
Nice project.
Calling `Nbgdb' results in a layout
```
+---------------+
|               |
|      gdb      |
|               |
+---------------+
|               |
|      file     |
|               |
+---------------+
```
And not the layout described in the docs

**Comment by huawenyu** [comment]
[According the suggest, only display two windows for gdb local](https://github.com/huawenyu/neogdb.vim/issues/1#issuecomment-292764823)
