### ISSUE TITLE
Error when executing 'GdbLocal'

### ISSUE THREAD

**Issue by alefa** [huawenyu/neogdb.vim#2]
This plugin is exactly what I was looking for, but unfortunately it doesn't work for me. To test it, I compiled the following "Hello world" program (hello.cc) with debug symbols:

```c++
    // a small C++ program
    #include <iostream>
    
    int main()
    {
    	std::cout << "Hello, world!" << std::endl;
    	return 0;
    }
```

With the file open in Neovim, I then ran the command `:GdbLocal hello`. [Here's](https://imgur.com/a/l6WOw) an image of the error message I got. Am I doing something wrong, or is that a bug? I'm using Neovim 0.1.7 on Debian Stretch, with neogdb.vim installed using Vim-plug.

**Comment by huawenyu** [comment]
Press F2, once for local gdb, twice for remote gdb.
For example:
once,   :GdbLocal confloc#me hello
twice,   :GdbRemote confos#me sysinit/init 10.1.1.125:444

**Comment by alefa** [comment]
Ok, thanks. I didn't understand what `confloc#me` and `confos#me` are, and figured that these are optional arguments to the functions. In the screencast, you appear to use the `Gdblocal` command just with the name of the binary.
Have you considered writing a proper help file for the plugin where things like this are documented? I think that would make it easier to use, and avoid repeated questions from users like me. Personally, I would also make the key bindings optional and/or configurable, because some people may want to map the F-keys to other functions.

**Comment by huawenyu** [comment]
Thanks for you suggestion.

1. Sorry for the screencast, it's a little old.
2. the config files 'confloc#me' and 'confos#me' are special for different debug mode:
- confloc#me: the config for local(loc) and carried with the plugin.
- confos#me: the config for embedded os(os) and carried with the plugin.

So we can create our own config files and pass it to GdbLocal or GdbRemote to control different layout.
3. About the mapped F-keys, I'll add a option to bind it or not.
