### ISSUE TITLE
What should I do when I want to attach local pid?

### ISSUE THREAD

**Issue by ghost** [huawenyu/neogdb.vim#7]
What should I do when I want to attach local pid?

**Comment by huawenyu** [comment]
1. Suppost there have two terminal: terminal-app, terminal-vim
2. In terminal-app: used to run a program which should keep running until attached, here for example **t1**
    `$ ./t1`
3. Please use `$ ps -ef | grep t1` to get **pid**
    For example is **123**.
4. The terminal-vim run neovim:  `$ nvim t1.c`
2. Then in vim-command, `:Nbgdbattach t1 <pid>`, here is:
        **:Nbgdbattach t1 123**

**Comment by ghost** [comment]
When try `:Nbgdbattach pid/bin` report error:
![screenshot_20180126_153730](https://user-images.githubusercontent.com/20379044/35429582-9a5488ba-02af-11e8-95bb-0314a273968f.png)

@Cosson2017 how about **:Nbgdbattach bin pid**?
