### ISSUE TITLE
module[gdb] does not exist

### ISSUE THREAD

**Issue by Rmmichael95** [huawenyu/neogdb.vim#8]
I love the idea of this addon but can't figure out why it won't load. This is the error I get when I run Nbgdb filename from my nvim. Is there something I am doing wrong in setting up the plugin?
![2018-02-04_17 11 18](https://user-images.githubusercontent.com/8621104/35784623-a610f51c-0a11-11e8-809b-83ce3ce1b2e5.png)

**Comment by huawenyu** [comment]
I'm not sure what happened in your env, but could you test the existed test sample t1.c which I have already append the workflow into the readme.md, please check these following paragraph:
- **Sample**:   how to start the sample t1
- **Troubleshooting by log**:   how to enable log system, you can post the log here for the troubleshooting.

**Comment by Rmmichael95** [comment]
Unknown function: logger#init. Is the function from your plugin?

**Comment by huawenyu** [comment]
Could you double check the this plugin already installed:
**Plug 'huawenyu/vimlogger'**

**Comment by Rmmichael95** [comment]
[vim.log](https://github.com/huawenyu/neogdb.vim/files/1693902/vim.log)

**Comment by huawenyu** [comment]
Thanks for you testing env and upload log.

Checked the log, seemed like it's impossible to run like this. It's so sad I can't reproduce myself.
I've added more log info to the debug log, you can try this new verbose log version.

**Comment by Rmmichael95** [comment]
[vim.log](https://github.com/huawenyu/neogdb.vim/files/1694062/vim.log)

I don't think anything changed. It's a shame, this is plugin is exactly what I wanted for gdb.

**Comment by Rmmichael95** [comment]
[vim.log](https://github.com/huawenyu/neogdb.vim/files/1694130/vim.log)

I did a manual git pull anf this log has updated

**Comment by huawenyu** [comment]
Thanks for the log.

**Comment by huawenyu** [comment]
Checked the log, it's really the gdb.local.new() call fail, the detail fail can be check by command
`:message`. 
It's weird not working. ☺

**Comment by Rmmichael95** [comment]
![2018-02-04_23 26 18](https://user-images.githubusercontent.com/8621104/35792606-e9d9e86a-0a45-11e8-8185-254af72656e1.png)

 I don't know if I used the command correctly. This was the output.

**Comment by huawenyu** [comment]
### bug, fixed in the new version, please try.
#### cause: 
if define `g:neobugger_leader`, cause `g:gdb_require_enter_after_toggling_breakpoint` not define.

#### patch:
```diff
--- a/plugin/neobugger.vim
+++ b/plugin/neobugger.vim
@@ -104,9 +104,11 @@ else
         let g:gdb_keymap_frame_down = '<c-p>'
     endif

-    if !exists("g:gdb_require_enter_after_toggling_breakpoint")
-        let g:gdb_require_enter_after_toggling_breakpoint = 0
-    endif
+endif
+
+
+if !exists("g:gdb_require_enter_after_toggling_breakpoint")
+    let g:gdb_require_enter_after_toggling_breakpoint = 0
 endif
```

**Comment by Rmmichael95** [comment]
![2018-02-05_08 25 43](https://user-images.githubusercontent.com/8621104/35815787-3dad4dc4-0a91-11e8-9a99-48910fe5fb0d.png)

Great. Seems to be working now. Thanks for the help. My window setup is different from yours. Is there a setting to turn on the breakpoint and backtrace watchers?

**Comment by huawenyu** [comment]
Add config to support it.
- Check the readme:  **### config windows**
- Plaintext here: add the following to .vimrc:
```vim
let g:neogdb_window = ['backtrace', 'breakpoint']
```

**Comment by Rmmichael95** [comment]
Thank you for all the help.
